# @package _global_
defaults:
  - override /model: deep4net
  # - override /data: tiny_dataset
  - override /trainer: base_trainer
hydra:
  run:
    dir: outputs/deep4net/${now:%Y-%m-%d}/${now:%H-%M-%S}