defaults:
  - base_model_config

model_name: atcnet
configs:
  model_name_or_path: atcnet
  from_pretrained: False
  pretrained_checkpoint: null
model_args:
  n_chans: 16
  n_outputs: 6
  n_times: 10000
  conv_block_n_filters: 8
  att_num_heads: 1
  add_log_softmax: false